### PR TITLE
Update alluxio-fuse csi

### PR DESCRIPTION
**Pull request by Binyang2014**
1. Format code
2. Add deploy script and example
3. Remove deprecated options, such as alluxio.master.port 

Notice: docker image: `alluxio/alluxio-csi:2.2.1` is invalid. But tested with my own build image.

### CODE REVIEW

**Comment by Binyang2014** [comment]
@madanadit take a look?

**Review by madanadit — COMMENTED** [review]
Thanks @Binyang2014 for your contribution! This looks great, do you mind adding a short section to the README (https://github.com/Alluxio/alluxio-csi/blob/master/README.md) w/ how to
- build the docker image alluxio-csi
- install the k8s plugin
- run the example you've included

As a follow up to this PR, I can help with:
1. Publishing official docs to alluxio.io (csi driver in preview)
2. Publishing the docker image `alluxio-csi` 
2. Version management for this repo to keep up with core Alluxio releases

**Comment by Binyang2014** [comment]
@madanadit doc updated

**Review by madanadit — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
